### ISSUE TITLE
RuntimeError: shape '[1, 1, -1, 508, 508]' is invalid for input of size 16451136

### ISSUE THREAD

**Issue by zcq-debug** [VinAIResearch/MagNet#22]

**Comment by zcq-debug** [comment]
Traceback (most recent call last):
    main()
  File "E:\anaconda\envs\MagNet\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "demo.py", line 229, in main
    error_score = median_blur(error_score)
  File "E:\anaconda\envs\MagNet\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\MagNet-main\magnet\utils\blur.py", line 184, in forward
    x = x.view(b, c, -1, h, w)
RuntimeError: shape '[1, 1, -1, 508, 508]' is invalid for input of size 16451136

**Comment by hmchuong** [comment]
Can you give me the script you were running?

**Comment by hmchuong** [comment]
closes as no response
